# Generated by Django 6.0.6 on 2026-06-28 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockholding',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stockholding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
